// src/lib/config/firmware.ts

// Generated by scripts/fetch-latest-firmware.mjs (the `prebuild` step), which
// downloads the latest GitHub release UF2 into static/firmware/. The firmware
// is served same-origin: GitHub's release-asset CDN sends no CORS headers, so
// the browser could not fetch the bytes for the SysEx upload directly.
import manifest from './firmwareManifest.json';

/**
 * Gets the bundled firmware version and same-origin download URL.
 */
export async function getLatestFirmware(): Promise<{
	version: string;
	downloadUrl: string;
	size?: number;
}> {
	return {
		version: manifest.version,
		downloadUrl: `/firmware/${manifest.file}`,
		size: manifest.size
	};
}

/**
 * Gets the bundled firmware version synchronously.
 */
export function getCurrentFirmwareVersion(): string {
	return manifest.version;
}
